/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/top-bill-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supported bill categories
         * @description Returns all bill categories available for the given country (default NG).
         */
        get: operations["getBillCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{category}/billers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get billers for a category
         * @description Returns all billers (providers) available for the given category code.
         */
        get: operations["getBillProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billers/{biller_code}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get bill items for a biller
         * @description Returns packages/items for a specific biller, including item_code and amount.
         */
        get: operations["getBillItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bill-items/{item_code}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate a bill customer
         * @description Validate a customer's identifier (phone number, meter number, smartcard number, etc.) before making a payment. Not required for AIRTIME or MOBILEDATA.
         */
        get: operations["validateBillCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billers/{biller_code}/items/{item_code}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay a bill
         * @description Initiate a bill payment for a specific biller and item.
         */
        post: operations["payBill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{reference}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get bill payment status
         * @description Check the status of a bill payment using the tx_ref returned from pay_bill.
         */
        get: operations["getBillStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BillCategory: {
            /** @example 1 */
            id?: number;
            /** @example Airtime */
            name?: string;
            /** @example AIRTIME */
            code?: string;
            /** @example Buy airtime for any Nigerian network */
            description?: string;
            /** @example NG */
            country_code?: string;
        };
        Biller: {
            id?: number;
            /** @example MTN Nigeria */
            name?: string;
            /** @example BIL099 */
            biller_code?: string;
            /** @example MTN */
            short_name?: string;
            description?: string;
            /** @example NG */
            country_code?: string;
        };
        BillItem: {
            /** @example AT099 */
            item_code?: string;
            /**
             * @description The input label to show to the customer (e.g. "Phone Number", "Meter Number").
             * @example Phone Number
             */
            label_name?: string;
            /**
             * @description Fixed amount for this item. 0 means user-defined amount.
             * @example 0
             */
            amount?: number;
            id?: number;
            biller_code?: string;
            name?: string;
            short_name?: string;
            fee?: number;
            is_resolvable?: boolean;
        };
        BillValidation: {
            /** @example 00 */
            response_code?: string;
            /** @example Successful */
            response_message?: string;
            /**
             * @description Customer name returned by the biller.
             * @example John Doe
             */
            name?: string;
            biller_code?: string;
            customer?: string;
            product_code?: string;
            address?: string | null;
            email?: string | null;
            fee?: number;
            minimum?: number;
            maximum?: number;
        };
        BillPaymentResult: {
            phone_number?: string;
            amount?: number;
            network?: string;
            code?: string;
            /** @description Transaction reference — use with get_bill_status to check status. */
            tx_ref?: string;
            /** @description Your custom reference. */
            reference?: string;
            batch_reference?: string | null;
            /** @description Token for prepaid electricity meters. */
            recharge_token?: string | null;
            fee?: number;
        };
        BillStatus: {
            /** @example NGN */
            currency?: string;
            customer_id?: string;
            amount?: string;
            fee?: number;
            product?: string;
            product_name?: string | null;
            transaction_date?: string;
            customer_reference?: string;
            country?: string;
            flw_ref?: string;
            tx_ref?: string;
            /** @description Contains meter token for prepaid electricity payments. */
            extra?: string | null;
            product_details?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBillCategories: {
        parameters: {
            query?: {
                /** @description Country code. Currently only NG is supported. */
                country?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bill categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["BillCategory"][];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBillProviders: {
        parameters: {
            query?: {
                country?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Category code (e.g. AIRTIME, CABLEBILLS, UTILITYBILLS).
                 * @example CABLEBILLS
                 */
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of billers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["Biller"][];
                    };
                };
            };
            /** @description Invalid category. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBillItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Biller code from get_bill_providers (e.g. BIL119 for DSTV).
                 * @example BIL119
                 */
                biller_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bill items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["BillItem"][];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateBillCustomer: {
        parameters: {
            query: {
                /**
                 * @description Customer identifier (phone number, smartcard number, meter number, etc.).
                 * @example 08038291822
                 */
                customer: string;
            };
            header?: never;
            path: {
                /**
                 * @description Item code from get_bill_items.
                 * @example CB140
                 */
                item_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer validation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["BillValidation"];
                    };
                };
            };
            /** @description Invalid customer. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payBill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Biller code from get_bill_providers.
                 * @example BIL119
                 */
                biller_code: string;
                /**
                 * @description Item code from get_bill_items.
                 * @example CB140
                 */
                item_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Country code — must be NG.
                     * @example NG
                     */
                    country: string;
                    /**
                     * @description Customer identifier (phone, meter number, smartcard, etc.).
                     * @example 08038291822
                     */
                    customer_id: string;
                    /**
                     * @description Amount to pay. Must match the amount from get_bill_items for fixed-amount bills.
                     * @example 200
                     */
                    amount: number;
                    /**
                     * @description Your unique reference for tracking. Auto-generated if not provided.
                     * @example BILL-MTN-20240610-001
                     */
                    reference?: string;
                    /**
                     * @description URL for webhook notifications when the bill payment completes.
                     * @example https://myapp.com/webhooks/bills
                     */
                    callback_url?: string;
                };
            };
        };
        responses: {
            /** @description Bill payment initiated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["BillPaymentResult"];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBillStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The tx_ref or reference returned from pay_bill.
                 * @example BILL-MTN-20240610-001
                 */
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bill payment status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["BillStatus"];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
