/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Charge a payment method
         * @description Directly charge a customer using the specified payment method type.
         */
        post: operations["createCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate-charge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a charge with OTP
         * @description Validate a pending charge that requires OTP authorisation (card, account, or USSD).
         */
        post: operations["validateCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChargeResponse: {
            /** @example success */
            status?: string;
            /** @example Charge initiated */
            message?: string;
            data?: {
                /** @example 4975363 */
                id?: number;
                /** @example MC-158523s09v5050e8 */
                tx_ref?: string;
                /** @example FLW-MOCK-1e9e0e0e0e0e0e0e */
                flw_ref?: string;
                /** @example pending */
                status?: string;
                /** @example 100 */
                amount?: number;
                /** @example NGN */
                currency?: string;
                /** @example normal */
                charge_type?: string;
                /**
                 * @description Auth model used by the card (e.g. PIN, VBVSECURECODE)
                 * @example PIN
                 */
                auth_model?: string;
                /** @example Approved */
                processor_response?: string;
            };
            /** @description Present when further authorization steps are required. */
            meta?: {
                authorization?: {
                    /**
                     * @description The next required action.
                     * @enum {string}
                     */
                    mode?: "pin" | "avs_noauth" | "otp" | "redirect";
                    /** @description Fields needed from the customer (PIN or AVS flows). */
                    fields?: string[];
                    /** @description Redirect URL for 3DS authentication. */
                    redirect?: string;
                    /** @description Endpoint for OTP validation. */
                    endpoint?: string;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCharge: {
        parameters: {
            query: {
                /** @description The payment method type to charge. */
                type: "card" | "account" | "mobile_money_ghana" | "enaira" | "qr" | "mono" | "debit_uk_account" | "ach_payment" | "bank_transfer" | "mobile_money_tanzania" | "mobile_money_uganda" | "mobile_money_rwanda" | "mobile_money_zambia" | "mobile_money_francophone" | "mpesa" | "ussd" | "capitec" | "fawry_pay" | "opay" | "voucher_payment";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example encrypted_card_data_here */
                    client?: string;
                    /** @example MC-158523s09v5050e8 */
                    tx_ref?: string;
                    /** @example 100 */
                    amount?: string;
                    /** @example NGN */
                    currency?: string;
                    /** @example user@example.com */
                    email?: string;
                    /** @example Yemi Desola */
                    fullname?: string;
                    /** @example 09000000000 */
                    phone_number?: string;
                    /** @example https://example.com/callback */
                    redirect_url?: string;
                    /** @example 5531886652142950 */
                    card_number?: string;
                    /** @example 564 */
                    cvv?: string;
                    /** @example 09 */
                    expiry_month?: string;
                    /** @example 32 */
                    expiry_year?: string;
                    /** @example 044 */
                    account_bank?: string;
                    /** @example 0690000031 */
                    account_number?: string;
                    /** @example MTN */
                    network?: string;
                    /**
                     * @description Card holder name (required for AMEX transactions)
                     * @example John Doe
                     */
                    card_holder_name?: string;
                    /** @description Authorization data for PIN or AVS flows — second call only, after initial charge returns the required mode. */
                    authorization?: {
                        /**
                         * @description Authorization mode returned by the initial charge response.
                         * @enum {string}
                         */
                        mode?: "pin" | "avs_noauth";
                        /** @description Card PIN (for pin mode) */
                        pin?: string;
                        city?: string;
                        address?: string;
                        state?: string;
                        country?: string;
                        zipcode?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Charge initiated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeResponse"];
                };
            };
            /** @description Bad request, invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateCharge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 12345 */
                    otp: string;
                    /** @example FLW-MOCK-1e9e0e0e0e0e0e0e */
                    flw_ref: string;
                    /** @example card */
                    type?: string;
                };
            };
        };
        responses: {
            /** @description Charge validated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
