/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process a payment through Flutterwave
         * @description Initiates a payment process through Flutterwave using a unique transaction reference.
         */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/link/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable a Flutterwave payment link
         * @description Disables a specific payment link for the given URL.
         */
        post: operations["disablePaymentLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Transaction: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Payment data for the transaction */
        requestBody?: {
            content: {
                "application/json": {
                    /** @example txnref_djsdkjsnkdjvnsdfj */
                    tx_ref: string;
                    /** @example 7500 */
                    amount: string;
                    /** @example NGN */
                    currency: string;
                    /** @example https://example_company.com/success */
                    redirect_url: string;
                    customer: {
                        /** @example developers@flutterwavego.com */
                        email?: string;
                        /** @example Flutterwave Developers */
                        name?: string;
                        /** @example 09012345678 */
                        phonenumber?: string;
                    };
                    customizations: {
                        /** @example Flutterwave Standard Payment */
                        title?: string;
                    };
                };
            };
        };
        responses: never;
    };
    disablePaymentLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Payment link data to disable */
        requestBody?: {
            content: {
                "application/json": {
                    /** @example https://checkout.flutterwave.com/v3/hosted/pay/flwlnk-01j8hkejppgm821xv8mfxfpgrb */
                    link: string;
                };
            };
        };
        responses: {
            /** @description Payment link disabled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Payment link has been disabled successfully */
                        message?: string;
                    };
                };
            };
            /** @description Bad request, invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payment link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
