/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rfq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an FX Quote (RFQ)
         * @description Submit a request for an exchange-rate quote for the given currency pair and quantity. The quote is processed asynchronously — poll GET /rfq/{id} or wait for the quote.completed webhook. Minimum trade is $1,000 USD equivalent. Quotes with duplicate references will error.
         */
        post: operations["requestFxQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfq/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get FX Quote status
         * @description Retrieve the current status and pricing of an RFQ. Poll this until status is READY (then initiate a trade) or FAILED. READY quotes expire after 5 minutes.
         */
        get: operations["getFxQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate an FX Trade
         * @description Execute a trade using a READY quote. Locks in the rate and debits the base currency from your wallet. The quote must be in READY status and not yet expired. A quote can only be used once.
         */
        post: operations["initiateFxTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trade/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get FX Trade status
         * @description Retrieve the current status of a trade. Poll until status is SETTLED (funds exchanged) or FAILED. Upon settlement, converted funds land instantly in the target currency wallet.
         */
        get: operations["getFxTrade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FxQuoteData: {
            /**
             * @description Real-time exchange rate applied to the conversion.
             * @example 0.000659
             */
            best_available_rate?: string;
            /**
             * @description Actual base_currency amount approved for the trade. May differ from requested quantity due to liquidity or account limits.
             * @example 1517759
             */
            approved_quantity?: number;
            /**
             * @description Final converted amount in target_currency (approved_quantity × rate).
             * @example 1000.203181
             */
            total_value?: number;
            /**
             * Format: date-time
             * @description Timestamp after which the quote can no longer be used.
             * @example 2026-02-06T10:12:02.990Z
             */
            expiry?: string;
        };
        FxQuoteResponse: {
            /** @example success */
            status?: string;
            /** @example Request for quote submitted. */
            message?: string;
            data?: {
                /**
                 * @description Unique quote ID — use this with GET /rfq/{id} and POST /trade.
                 * @example c085aab5-5938-46a7-90a9-22420c2a8d6e
                 */
                id?: string;
                /** @example c9f6539747ef11f1 */
                reference?: string;
                /**
                 * @description Requested base_currency amount.
                 * @example 1617759
                 */
                quantity?: number;
                /**
                 * @description Currency pair (e.g. NGN/USD).
                 * @example NGN/USD
                 */
                instrument?: string;
                /** @description Null until status is READY. */
                quote?: components["schemas"]["FxQuoteData"] | null;
                /**
                 * @example READY
                 * @enum {string}
                 */
                status?: "NEW" | "READY" | "PROCESSING" | "EXPIRED" | "FAILED";
                /** @example Your RFQ is ready */
                complete_message?: string | null;
                /**
                 * Format: date-time
                 * @example 2026-02-06T10:03:22.000Z
                 */
                created_at?: string;
            };
        };
        FxRecipient: {
            /** @example 200004751 */
            id?: string;
            /** @example MythCo. */
            name?: string;
        };
        FxTradeResponse: {
            /** @example success */
            status?: string;
            /** @example Trade initiated successfully. */
            message?: string;
            data?: {
                /**
                 * @description Unique trade ID — use with GET /trade/{id} to poll status.
                 * @example 30b85c03-9124-4418-b30b-0495ffbdc633
                 */
                id?: string;
                /**
                 * @description Original requested base_currency amount.
                 * @example 1617759
                 */
                quantity?: number;
                /**
                 * @description Actual base_currency amount approved for the trade.
                 * @example 1517759
                 */
                approved_quantity?: number;
                /**
                 * @description Final converted amount in target_currency.
                 * @example 1000.203181
                 */
                price?: number;
                /**
                 * @description Currency pair.
                 * @example NGN/USD
                 */
                instrument?: string;
                /**
                 * @example SETTLED
                 * @enum {string}
                 */
                status?: "NEW" | "PENDING" | "FAILED" | "SETTLED";
                /** @example Transfer was Successful */
                response_message?: string | null;
                recipient?: components["schemas"]["FxRecipient"];
                /** @example Q1 vendor payment conversion */
                narration?: string;
                /** @example TRD-86ade016977958e2 */
                reference?: string;
                /** @example https://myapp.com/webhooks/fx */
                callback_url?: string | null;
                /**
                 * Format: date-time
                 * @example 2026-02-06T10:08:54.000Z
                 */
                created_at?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestFxQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Currency being sold / converted from.
                     * @example NGN
                     * @enum {string}
                     */
                    base_currency: "NGN" | "GHS" | "USD";
                    /**
                     * @description Currency being received / converted into.
                     * @example USD
                     * @enum {string}
                     */
                    target_currency: "NGN" | "GHS" | "USD";
                    /**
                     * @description Amount of base_currency to convert.
                     * @example 1617759
                     */
                    quantity: number;
                    /**
                     * @description Your unique reference for this quote. Auto-generated if omitted. Must be unique — a duplicate reference returns an error.
                     * @example FX-NGN-USD-001
                     */
                    reference?: string;
                    /**
                     * @description Test mode only. Do not use in production.
                     * @enum {string}
                     */
                    scenario?: "ready" | "expired" | "invalid_amount" | "invalid_currency_pair" | "exceeded_limit";
                };
            };
        };
        responses: {
            /** @description Quote request accepted. Poll GET /rfq/{id} for status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxQuoteResponse"];
                };
            };
            /** @description Bad request — missing fields, duplicate reference, or unsupported pair. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFxQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id returned from POST /rfq.
                 * @example c085aab5-5938-46a7-90a9-22420c2a8d6e
                 */
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote details with current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxQuoteResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    initiateFxTrade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description ID of a READY quote from GET /rfq/{id}.
                     * @example c085aab5-5938-46a7-90a9-22420c2a8d6e
                     */
                    quote_id: string;
                    /**
                     * @description Short note describing the purpose of the trade.
                     * @example Q1 vendor payment conversion
                     */
                    narration: string;
                };
            };
        };
        responses: {
            /** @description Trade initiated. Poll GET /trade/{id} for settlement status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxTradeResponse"];
                };
            };
            /** @description Bad request — quote does not exist, expired, or already used. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFxTrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id returned from POST /trade.
                 * @example 30b85c03-9124-4418-b30b-0495ffbdc633
                 */
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trade details with current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxTradeResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
