/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate a Transfer request
         * @description Initiates a transfer through Flutterwave using a unique transaction reference.
         */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/{id}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Transfer details
         * @description Retry a transfer using its transfer ID.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique transaction ID. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transfer retry attempt queued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example success */
                            status?: string;
                            /** @example Transfer retry attempt queued. */
                            message?: string;
                            data?: {
                                /** @example 4975363 */
                                id?: number;
                                /** @example TRF-640361604052_RETRY_2 */
                                reference?: string;
                                /**
                                 * Format: float
                                 * @example 1000
                                 */
                                amount?: number;
                                /**
                                 * Format: float
                                 * @example 1000
                                 */
                                fee?: number;
                                /** @example 1234567841 */
                                account_number?: string;
                                /** @example NGN */
                                currency?: string;
                                /** @example ACCESS BANK NIGERIA */
                                bank_name?: string;
                                /** @example John Doe */
                                full_name?: string;
                                /** @example NGN */
                                debit_currency?: string;
                                /** @example NEW */
                                status?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-03-19T09:34:27.000Z
                                 */
                                created_at?: string;
                            };
                        };
                    };
                };
                /** @description Bad request, invalid transaction ID. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example error */
                            status?: string;
                            /** @example Invalid Transaction ID */
                            message?: string;
                            data?: Record<string, never> | null;
                        };
                    };
                };
                /** @description Transaction not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example error */
                            status?: string;
                            /** @example Transaction not found */
                            message?: string;
                            data?: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate a Bulk Transfer request
         * @description Initiates a bulk transfer through Flutterwave using a unique transaction reference.
         */
        post: operations["createBulkTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List beneficiaries
         * @description Retrieve a paginated list of beneficiaries. Supports the `page` query parameter.
         */
        get: operations["listBeneficiaries"];
        put?: never;
        /**
         * Create a beneficiary
         * @description Create a transfer beneficiary. Example request body matches Flutterwave's create beneficiary endpoint.
         */
        post: operations["createBeneficiary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        transfer: {
            /** @example john@example.com */
            email?: string;
            /** @example 2349012345678 */
            mobile_number?: string;
            /** @example 7A, Super Street, Awesome Address, Smart State, NG */
            recipient_address?: string;
            /** @example Abraham */
            first_name?: string;
            /** @example Olaobaju */
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Transfer data for the transaction */
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 044 */
                    account_bank: string;
                    /** @example 0690000040 */
                    account_number: string;
                    /** @example 5500 */
                    amount: number;
                    /** @example NGN */
                    currency: string;
                    /** @example PSA******07974 */
                    debit_subaccount?: string;
                    /** @example 3768 */
                    beneficiary?: number;
                    /** @example Yemi Desola */
                    beneficiary_name?: string;
                    /** @example newFLWXTransfer123 */
                    reference?: string;
                    /** @example NGN */
                    debit_currency?: string;
                    /** @example GH280103 */
                    destination_branch_code?: string;
                    /** @example Payment for goods purchased */
                    narration?: string;
                    /** @example https://example_company.com/success */
                    callback_url?: string;
                    meta?: {
                        /** @example John Avery Doe */
                        sender?: string;
                        /** @example 123 Sample Street, Cambuslang, AB12 345 */
                        sender_address?: string;
                        /** @example Glasgow */
                        sender_city?: string;
                        /** @example United Kingdom */
                        sender_country?: string;
                        /** @example John */
                        first_name?: string;
                        /** @example Doe */
                        last_name?: string;
                        /** @example john@example.com */
                        email?: string;
                        /** @example +23490XXXXX23 */
                        mobile_number?: string;
                        /** @example +23490XXXXX25 */
                        beneficiary_mobile_number?: string;
                        /** @example 456 Sample Street, Motherwell, CD12 345 */
                        recipient_address?: string;
                        /** @example Scotland */
                        beneficiary_state?: string;
                        /** @example United Kingdom */
                        beneficiary_country?: string;
                        /** @example Software Engineer */
                        beneficiary_occupation?: string;
                        /** @example Pocket Money */
                        transfer_purpose?: string;
                    };
                };
            };
        };
        responses: never;
    };
    createBulkTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bulk Transfer data for the transaction */
        requestBody?: {
            content: {
                "application/json": {
                    /** @example NGN */
                    currency: string;
                    bulk_data: components["schemas"]["transfer"][];
                };
            };
        };
        responses: never;
    };
    listBeneficiaries: {
        parameters: {
            query?: {
                /** @description Page number to retrieve */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of beneficiaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "success",
                     *       "message": "Payout beneficiaries fetched",
                     *       "meta": {
                     *         "page_info": {
                     *           "total": 9,
                     *           "current_page": 1,
                     *           "total_pages": 1
                     *         }
                     *       },
                     *       "data": [
                     *         {
                     *           "id": 3768,
                     *           "account_number": "0690000040",
                     *           "bank_code": "044",
                     *           "full_name": "Alexis Sanchez",
                     *           "meta": null,
                     *           "created_at": "2020-01-20T16:09:24.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 3690,
                     *           "account_number": "0690000039",
                     *           "bank_code": "044",
                     *           "full_name": "Dotun Ajib",
                     *           "meta": null,
                     *           "created_at": "2020-01-19T22:36:06.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 3644,
                     *           "account_number": "0690000034",
                     *           "bank_code": "044",
                     *           "full_name": "Ade Bond",
                     *           "meta": null,
                     *           "created_at": "2020-01-16T18:01:28.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 3608,
                     *           "account_number": "0690000044",
                     *           "bank_code": "044",
                     *           "full_name": "Mercedes Daniel",
                     *           "meta": null,
                     *           "created_at": "2020-01-15T11:58:02.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 3565,
                     *           "account_number": "0690000038",
                     *           "bank_code": "044",
                     *           "full_name": "John Sunday",
                     *           "meta": null,
                     *           "created_at": "2020-01-14T05:53:34.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 3104,
                     *           "account_number": "2540782773934",
                     *           "bank_code": "000",
                     *           "full_name": "Kwame Adew",
                     *           "meta": null,
                     *           "created_at": "2019-12-05T23:49:31.000Z",
                     *           "bank_name": "FA-BANK"
                     *         },
                     *         {
                     *           "id": 3093,
                     *           "account_number": "0690000041",
                     *           "bank_code": "044",
                     *           "full_name": "Alexis Rogers",
                     *           "meta": null,
                     *           "created_at": "2019-12-05T21:29:57.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 2923,
                     *           "account_number": "0690000032",
                     *           "bank_code": "044",
                     *           "full_name": "Pastor Bright",
                     *           "meta": null,
                     *           "created_at": "2019-11-28T08:15:29.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         },
                     *         {
                     *           "id": 2857,
                     *           "account_number": "0690000031",
                     *           "bank_code": "044",
                     *           "full_name": "Forrest Green",
                     *           "meta": null,
                     *           "created_at": "2019-11-20T10:33:20.000Z",
                     *           "bank_name": "ACCESS BANK NIGERIA"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Payout beneficiaries fetched */
                        message?: string;
                        meta?: {
                            page_info?: {
                                /** @example 9 */
                                total?: number;
                                /** @example 1 */
                                current_page?: number;
                                /** @example 1 */
                                total_pages?: number;
                            };
                        };
                        data?: {
                            /** @example 3768 */
                            id?: number;
                            /** @example 0690000040 */
                            account_number?: string;
                            /** @example 044 */
                            bank_code?: string;
                            /** @example Alexis Sanchez */
                            full_name?: string;
                            meta?: Record<string, never> | null;
                            /**
                             * Format: date-time
                             * @example 2020-01-20T16:09:24.000Z
                             */
                            created_at?: string;
                            /** @example ACCESS BANK NIGERIA */
                            bank_name?: string;
                        }[];
                    };
                };
            };
        };
    };
    createBeneficiary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "account_bank": "044",
                 *       "account_number": "0690000032",
                 *       "beneficiary_name": "Flutterwave Developers",
                 *       "currency": "NGN",
                 *       "bank_name": "ACCESS BANK NIGERIA"
                 *     }
                 */
                "application/json": {
                    /** @example 044 */
                    account_bank: string;
                    /** @example 0690000032 */
                    account_number: string;
                    /** @example Flutterwave Developers */
                    beneficiary_name: string;
                    /** @example NGN */
                    currency: string;
                    /** @example ACCESS BANK NIGERIA */
                    bank_name?: string;
                };
            };
        };
        responses: {
            /** @description Beneficiary created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "success",
                     *       "message": "Beneficiary created",
                     *       "data": {
                     *         "id": 3644,
                     *         "account_number": "0690000034",
                     *         "bank_code": "044",
                     *         "full_name": "Ade Bond",
                     *         "created_at": "2020-01-16T18:01:28.000Z",
                     *         "bank_name": "ACCESS BANK NIGERIA"
                     *       }
                     *     }
                     */
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Beneficiary created */
                        message?: string;
                        data?: {
                            /** @example 3644 */
                            id?: number;
                            /** @example 0690000034 */
                            account_number?: string;
                            /** @example 044 */
                            bank_code?: string;
                            /** @example Ade Bond */
                            full_name?: string;
                            /**
                             * Format: date-time
                             * @example 2020-01-16T18:01:28.000Z
                             */
                            created_at?: string;
                            /** @example ACCESS BANK NIGERIA */
                            bank_name?: string;
                        };
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /** @example Invalid request */
                        message?: string;
                        data?: Record<string, never> | null;
                    };
                };
            };
        };
    };
}
