/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bvn/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate BVN verification (consent request)
         * @description Begin a BVN (Bank Verification Number) verification for a customer. Returns a single-use hosted consent URL that the customer must visit to approve data sharing on the NIBSS portal. If the customer already consented, url will be null and you can retrieve their data immediately via GET /bvn/verifications/{reference}. Requires account enablement — contact hi@flutterwavego.com.
         */
        post: operations["initiateBvnVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bvn/verifications/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve BVN verification details
         * @description Fetch the BVN data for a completed verification using its reference. Returns comprehensive identity data including name, DOB, gender, phone numbers, state of origin, and a face image (base64). Status will be COMPLETED when the customer has provided consent.
         */
        get: operations["getBvnDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a bank account number
         * @description Look up the account holder name for a bank account number. Use this to verify account details before initiating a transfer. Requires account_number (10 digits) and account_bank (bank code).
         */
        post: operations["resolveBankAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-bins/{bin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify a card BIN
         * @description Look up card metadata from the first 6 digits (BIN) of a card number. Returns issuer, card type (debit/credit), brand (Visa/Mastercard/AMEX), country of issue, and card subtype. Useful for validating cards before charging.
         */
        get: operations["verifyCardBin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Comprehensive identity data returned after customer consent. */
        BvnData: {
            /** @example 22415929481 */
            bvn?: string;
            /** @example 12345678901 */
            nin?: string | null;
            /** @example customer@example.com */
            email?: string | null;
            /** @example Male */
            gender?: string;
            /** @example Ade */
            surname?: string;
            /** @example Desola */
            firstName?: string;
            middleName?: string | null;
            /** @example 1990-01-15 */
            dateOfBirth?: string;
            /** @description Base64-encoded facial image. */
            faceImage?: string | null;
            /** @example +2348012345678 */
            phoneNumber1?: string;
            phoneNumber2?: string | null;
            maritalStatus?: string | null;
            /** @example Lagos */
            stateOfOrigin?: string;
            stateOfCapture?: string | null;
            stateOfResidence?: string | null;
            lgaOfOrigin?: string | null;
            lgaOfResidence?: string | null;
            nameOnCard?: string | null;
            watchlisted?: boolean | null;
        };
        BvnVerificationData: {
            /** @example Desola */
            first_name?: string;
            /** @example Ade */
            last_name?: string;
            /**
             * @example COMPLETED
             * @enum {string}
             */
            status?: "PENDING" | "COMPLETED";
            /** @example BVN-REF-20240610-001 */
            reference?: string;
            callback_url?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** @description Present only when status is COMPLETED. */
            bvn_data?: components["schemas"]["BvnData"];
        };
        CardBinData: {
            /** @example NG */
            "issuing-country"?: string;
            /** @example 553188 */
            bin?: string;
            /** @example CREDIT */
            "card-type"?: string;
            /** @example NEXUS MERCHANT BANK DEBIT PERSONAL */
            "issuer-info"?: string;
            /** @example NIGERIA */
            "iso-country-alpha2"?: string;
            /** @example MASTERCARD */
            brand?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initiateBvnVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 11-digit Bank Verification Number.
                     * @example 22415929481
                     */
                    bvn: string;
                    /**
                     * @description Customer's first name.
                     * @example Desola
                     */
                    firstname: string;
                    /**
                     * @description Customer's last name.
                     * @example Ade
                     */
                    lastname: string;
                    /**
                     * @description URL the customer is redirected to after completing consent on the NIBSS portal.
                     * @example https://myapp.com/bvn/callback
                     */
                    redirect_url: string;
                };
            };
        };
        responses: {
            /** @description Consent request initiated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Bvn verification initiated */
                        message?: string;
                        data?: {
                            /**
                             * @description Single-use consent page URL. Null if customer has already consented previously.
                             * @example https://bvn.flutterwave.com/consent/...
                             */
                            url?: string | null;
                            /**
                             * @description Unique reference for this verification — use with GET /bvn/verifications/{reference}.
                             * @example BVN-REF-20240610-001
                             */
                            reference?: string;
                        };
                    };
                };
            };
            /** @description Invalid BVN or missing required fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBvnDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Reference returned from POST /bvn/verifications.
                 * @example BVN-REF-20240610-001
                 */
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description BVN details retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Bvn details fetched */
                        message?: string;
                        data?: components["schemas"]["BvnVerificationData"];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 10-digit bank account number.
                     * @example 0690000040
                     */
                    account_number: string;
                    /**
                     * @description Bank code (3 digits). Use get_banks to look up codes.
                     * @example 044
                     */
                    account_bank: string;
                };
            };
        };
        responses: {
            /** @description Account resolved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Account details fetched */
                        message?: string;
                        data?: {
                            /** @example 0690000040 */
                            account_number?: string;
                            /** @example Desola Ade */
                            account_name?: string;
                        };
                    };
                };
            };
            /** @description Account not found or invalid parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyCardBin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description First 6 digits of the card number (Bank Identification Number).
                 * @example 553188
                 */
                bin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card BIN details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example Bin found */
                        message?: string;
                        data?: components["schemas"]["CardBinData"];
                    };
                };
            };
            /** @description Invalid BIN. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
