/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/virtual-account-numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a virtual account number
         * @description Create a static (permanent) or dynamic (one-time) virtual account number for a customer. NGN static accounts require a BVN. GHS accounts support frequency and duration for recurring collection.
         */
        post: operations["createVirtualAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-account-numbers/{order_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a virtual account by order_ref
         * @description Retrieve the details of a single virtual account using its order_ref.
         */
        get: operations["getVirtualAccount"];
        /**
         * Update a virtual account (BVN)
         * @description Update the BVN linked to a virtual account.
         */
        put: operations["updateVirtualAccount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk-virtual-account-numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List virtual accounts in bulk by batch ID
         * @description Retrieve all virtual accounts created in a bulk batch.
         */
        get: operations["listVirtualAccountBulk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VirtualAccountData: {
            /** @example 02 */
            response_code?: string;
            /** @example Transaction fetched successfully */
            response_message?: string;
            /** @example FLW-MOCK-VA-001 */
            flw_ref?: string;
            /** @example URF_1234567890_8044304_NG */
            order_ref?: string;
            /** @example 8044304553 */
            account_number?: string;
            /** @example 1 */
            frequency?: string;
            /** @example WEMA BANK */
            bank_name?: string;
            /** @example 2024-06-10T11:34:11.000Z */
            created_at?: string;
            /** @example 2024-06-10 12:34:11 */
            expiry_date?: string;
            /** @example Please make a bank transfer to Flutterwave MFB Bank with account number 8044304553 */
            note?: string;
            /** @example 5000 */
            amount?: number;
            /** @example user@example.com */
            email?: string;
            /** @example false */
            is_permanent?: boolean;
            /** @example active */
            account_status?: string;
            /** @example NGN */
            currency?: string;
        };
        VirtualAccountResponse: {
            /** @example success */
            status?: string;
            /** @example Virtual account created */
            message?: string;
            data?: components["schemas"]["VirtualAccountData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createVirtualAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example user@example.com */
                    email: string;
                    /**
                     * @example NGN
                     * @enum {string}
                     */
                    currency: "NGN" | "GHS";
                    /**
                     * @description Unique transaction reference for this account.
                     * @example VA-NGN-20240610-001
                     */
                    tx_ref: string;
                    /**
                     * @description Amount to collect. Required for dynamic accounts; omit or use 0 for static.
                     * @example 5000
                     */
                    amount?: number;
                    /**
                     * @description true creates a static (reusable) account; false (default) creates a dynamic one-time account.
                     * @example false
                     */
                    is_permanent?: boolean;
                    /**
                     * @description Bank Verification Number (11 digits). Required for NGN static accounts.
                     * @example 22415929481
                     */
                    bvn?: string;
                    /**
                     * @description Display name shown when the account is resolved at the bank.
                     * @example My Store Payments
                     */
                    narration?: string;
                    /**
                     * @description Customer phone number.
                     * @example +2349012345678
                     */
                    phonenumber?: string;
                    /** @example Adaeze */
                    firstname?: string;
                    /** @example Okonkwo */
                    lastname?: string;
                    /**
                     * @description GHS only — number of times the account can be used. Omit for unlimited.
                     * @example 5
                     */
                    frequency?: number;
                    /**
                     * @description GHS only — number of days the account stays active.
                     * @example 7
                     */
                    duration?: number;
                };
            };
        };
        responses: {
            /** @description Virtual account created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualAccountResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVirtualAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The order_ref returned when the virtual account was created.
                 * @example URF_1234567890_8044304_NG
                 */
                order_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual account details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualAccountResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateVirtualAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example URF_1234567890_8044304_NG */
                order_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Updated Bank Verification Number (11 digits).
                     * @example 22415929481
                     */
                    bvn: string;
                };
            };
        };
        responses: {
            /** @description Virtual account updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualAccountResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVirtualAccountBulk: {
        parameters: {
            query: {
                /**
                 * @description The batch_id returned when a bulk virtual account was created.
                 * @example b_ABCDEF123
                 */
                batch_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of virtual accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        message?: string;
                        data?: components["schemas"]["VirtualAccountData"][];
                    };
                };
            };
        };
    };
}
