openapi: 3.0.3
info:
  title: Flutterwave Transactions API
  description: API for managing and retrieving transaction details via Flutterwave.
  version: 1.0.0
servers:
  - url: https://api.flutterwave.com/v3
paths:
  /plans:
    post:
      summary: Create a new subscription plan
      description: Create a new subscription plan with specified details.
      operationId: createPlan
      requestBody:
        description: Plan data for the new subscription plan
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Premium Plan'
                amount:
                  type: integer
                  example: 5000
                interval:
                  type: string
                  example: 'monthly'
                duration:
                  type: integer
                  example: 12
                currency:
                  type: string
                  example: 'NGN'
              required:
                - name
                - amount
                - interval
                - duration
      responses:
        '200':
          description: Subscription plan created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  message:
                    type: string
                    example: 'Payment plan created'
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 'pln_123456789'
                      name:
                        type: string
                        example: 'Premium Plan'
                      amount:
                        type: integer
                        example: 5000
                      interval:
                        type: string
                        example: 'monthly'
                      duration:
                        type: integer
                        example: 12
                      currency:
                        type: string
                        example: 'NGN'
                      status:
                        type: string
                        example: 'active'
                      plan_token:
                        type: string
                        example: 'pln_tok_abcdef123456'
                      created_at:
                        type: string
                        format: date-time
                        example: '2023-01-01T00:00:00Z'
    get:
      summary: Retrieve all subscription plans
      description: Fetch a list of all subscription plans.
      operationId: getPlans
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Page number for pagination
        - in: query
          name: amount
          schema:
            type: integer
            example: 10
          description: This is the exact amount set when creating the payment plan
        - in: query
          name: currency
          schema:
            type: string
            example: 'NGN'
          description: This is the currency used for the payment plan
        - in: query
          name: status
          schema:
            type: string
            example: 'active'
          description: This is the status of the payment plan
        - in: query
          name: interval
          schema:
            type: string
            example: 'monthly'
          description: This is the interval of the payment plan
        - in: query
          name: from
          schema:
            type: string
            example: '2023-01-01'
          description: This is the start date for the payment plan
        - in: query
          name: to
          schema:
            type: string
            example: '2023-12-31'
          description: This is the end date for the payment plan
      responses:
        '200':
          description: A list of subscription plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  message:
                    type: string
                    example: 'Payment plans fetched'
                  meta:
                    type: object
                    properties:
                      page_info:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 10
                          total_pages:
                            type: integer
                            example: 1 
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 'pln_123456789'
                        name:
                          type: string
                          example: 'Premium Plan'
                        amount:
                          type: integer
                          example: 5000
                        interval:
                          type: string
                          example: 'monthly'
                        duration:
                          type: integer
                          example: 12
                        currency:
                          type: string
                          example: 'NGN'
                        status:
                          type: string
                          example: 'active'
                        created_at:
                          type: string
                          format: date-time
                          example: '2023-01-01T00:00:00Z'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT